Rarity of strings
exercism/abap pull request #252
Opened 2022-11-25 16:48 UTC by Ennowulff

I tried my best to create my first exercism...

2022-11-25 23:10 UTC, mbtools requested changes
Already pretty good. A few things...

- The exercise should go into the `exercises/practice` folder (not `concepts` since we don't have those yet)
- The file in `.meta` needs to be renamed. There's currently no better way than manually adding the `.meta`
- There are some changes to unrelated exercises in the `practice` folder. Those were caused by pushing from ABAP I assume. Please revert those changes to avoid a warning for all users who have already worked on the exercises. 

It looks like the exercise is new to the Exercism platform (it's not from https://github.com/exercism/problem-specifications/). We will need to request a new icon.

2022-11-25 23:10 UTC, mbtools commented on exercises/concept/rarity_of_string/.meta/config.json
> +    "solution": ["zcl_rarity_of_String.clas.abap"],
2x zcl_rarity_of_String > zcl_rarity_of_string

2022-11-25 23:10 UTC, mbtools commented on exercises/concept/rarity_of_string/.meta/zcl_rarity_of_String.abap
> +CLASS zcl_rarity_of_string DEFINITION
rename file zcl_rarity_of_String > zcl_rarity_of_string

2022-11-25 23:49 UTC, Ennowulff commented
> Already pretty good. A few things...

> * The exercise should go into the `exercises/practice` folder (not `concepts` since we don't have those yet)
Okay. I thought "concepts" is for new exercises to be reviewed

> * The file in `.meta` needs to be renamed. There's currently no better way than manually adding the `.meta`
Done.

> * There are some changes to unrelated exercises in the `practice` folder. Those were caused by pushing from ABAP I assume. Please revert those changes to avoid a warning for all users who have already worked on the exercises.
I don't understand what you mean 😢

> It looks like the exercise is new to the Exercism platform (it's not from https://github.com/exercism/problem-specifications/). We will need to request a new icon.
Of course it's new. That's the reason for the fork... 😀 Right, a new icon would be fine. Is there a How-To for new exercises?

2022-11-26 00:57 UTC, mbtools commented
please commit the changes to your branch :-)

With "new exercise" I meant that it does not exist in any programming language on Exercism. Example for requesting new icon:
https://github.com/exercism/website-icons/issues/126

2023-02-19 08:59 UTC, mbtools commented
bin im urlaub und melde mich naechste woche

2023-03-22 13:24 UTC, closed without merging